<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'paths.pluginRoot' => 'get1',
  'JdsDemoPlugin\\Config\\ConfigFactory' => 'get2',
  'JdsDemoPlugin\\Config\\TemplateConfig' => 'get3',
  'JdsDemoPlugin\\Config\\TwigTextExtractionConfig' => 'get4',
  'Twig\\Loader\\LoaderInterface' => 'get5',
  'Twig\\Environment' => 'get6',
  'JdsDemoPlugin\\Services\\TwigTextExtractor' => 'get7',
  'subEntry1' => 'get8',
  'subEntry2' => 'get9',
  'subEntry3' => 'get10',
  'JdsDemoPlugin\\WordPressApi\\Interfaces\\IWordPressMenuFactory' => 'get11',
  'subEntry4' => 'get12',
  'JdsDemoPlugin\\Plugin' => 'get13',
  'subEntry5' => 'get14',
  'JdsDemoPlugin\\Services\\FileSystem' => 'get15',
);

    protected function get1()
    {
        return 'C:\\workspace\\personal\\job-search\\wordpress\\jds-demo-plugin\\tests/_data/';
    }

    protected function get2()
    {
        return $this->resolveFactory(static function ( \Psr\Container\ContainerInterface $c ) {
				return new \JdsDemoPlugin\Config\ConfigFactory( $c->get( \JdsDemoPlugin\Services\FileSystem::class ), $c->get( 'paths.pluginRoot' ) );
			}, 'JdsDemoPlugin\\Config\\ConfigFactory');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function ( \Psr\Container\ContainerInterface $c ) {
				/** @var ConfigFactory $configFactory */
				$configFactory = $c->get( \JdsDemoPlugin\Config\ConfigFactory::class );

				return $configFactory->createTemplateConfig();
			}, 'JdsDemoPlugin\\Config\\TemplateConfig');
    }

    protected function get4()
    {
        return $this->resolveFactory(static function ( \Psr\Container\ContainerInterface $c ) {
				/** @var ConfigFactory $configFactory */
				$configFactory = $c->get( \JdsDemoPlugin\Config\ConfigFactory::class );

				return $configFactory->createTwigTextExtractionConfig();
			}, 'JdsDemoPlugin\\Config\\TwigTextExtractionConfig');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function ( \Psr\Container\ContainerInterface $c ) {
				/** @var TemplateConfig $templateConfig */
				$templateConfig = $c->get( \JdsDemoPlugin\Config\TemplateConfig::class );

				return new \Twig\Loader\FilesystemLoader( $templateConfig->templateRootPath );
			}, 'Twig\\Loader\\LoaderInterface');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function ( \Psr\Container\ContainerInterface $c ) {
				/** @var TemplateConfig $templateConfig */
				$templateConfig = $c->get( \JdsDemoPlugin\Config\TemplateConfig::class );

				$twig = new \Twig\Environment( $c->get( \Twig\Loader\LoaderInterface::class ), [
					'cache' => $templateConfig->templateCachePath
				] );

				$twig->addFunction( new \Twig\TwigFunction( '__', function ( $text ) {
					return __( $text, 'jds-demo-plugin-domain' );
				} ) );

				return $twig;
			}, 'Twig\\Environment');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('JdsDemoPlugin\\Config\\TwigTextExtractionConfig');
    }

    protected function get9()
    {
        return $this->delegateContainer->get('Twig\\Environment');
    }

    protected function get10()
    {
        return $this->delegateContainer->get('JdsDemoPlugin\\Services\\FileSystem');
    }

    protected function get7()
    {
        $object = new JdsDemoPlugin\Services\TwigTextExtractor($this->get8(), $this->get9(), $this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('Twig\\Environment');
    }

    protected function get11()
    {
        $object = new JdsDemoPlugin\WordPressApi\WordPressMenuFactory($this->get12());
        return $object;
    }

    protected function get14()
    {
        return $this->delegateContainer->get('JdsDemoPlugin\\WordPressApi\\Interfaces\\IWordPressMenuFactory');
    }

    protected function get13()
    {
        $object = new JdsDemoPlugin\Plugin($this->get14());
        return $object;
    }

    protected function get15()
    {
        $object = new JdsDemoPlugin\Services\FileSystem('C:\\workspace\\personal\\job-search\\wordpress\\jds-demo-plugin\\tests/_data/', true);
        return $object;
    }

}
