version: '3.9'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/nginx.dockerfile
    ports:
      - ${LOCAL_HTTP_PORT}:80
    volumes:
      - ../jds-demo-plugin:/var/www/html/wordpress/wp-content/plugins/jds-demo-plugin
    depends_on:
      - php
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./mysql/mysql.dockerfile
    restart: always
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_TEST_USER: ${MYSQL_TEST_USER}
      MYSQL_TEST_USER_PASSWORD: ${MYSQL_TEST_USER_PASSWORD}
  php:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./php/php.dockerfile
      args:
        dbname: ${MYSQL_DATABASE}
        dbuser: ${MYSQL_USER}
        dbpass: ${MYSQL_PASSWORD}
        dbhost: mysql
        url: nginx/wordpress
        title: ${SITE_TITLE}
        admin_user: ${ADMIN_USER}
        admin_password: ${ADMIN_PASSWORD}
        admin_email: ${ADMIN_EMAIL}
    volumes:
      - ../jds-demo-plugin:/var/www/html/wordpress/wp-content/plugins/jds-demo-plugin
