version: '3.9'
services:
  codeception:
    build:
      context: .
      dockerfile: ./codeception/codeception.dockerfile
#    entrypoint: ''
#    command: sleep infinity
      args:
        admin_user: ${ADMIN_USER}
        admin_password: ${ADMIN_PASSWORD}
    environment:
      PROTOCOL: http
    volumes:
      - ../jds-demo-plugin:/project
      - ./scripts:/opt/scripts
    depends_on:
      - chrome
      - php
      - nginx
  chrome:
    image: "selenium/standalone-chrome-debug:latest"



