version: '3.9'
services:
  codeception:
    build:
      context: .
      dockerfile: ./codeception/codeception.dockerfile
      args:
        admin_user: ${ADMIN_USER}
        admin_password: ${ADMIN_PASSWORD}
        dbname: ${MYSQL_DATABASE}
        dbuser: ${MYSQL_USER}
        dbpass: ${MYSQL_PASSWORD}
        dbhost: mysql
#    entrypoint: ''
#    command: sleep infinity
    environment:
      PROTOCOL: http
    volumes:
      - ../jds-demo-plugin:/project
      - ./scripts:/opt/scripts
    depends_on:
      - chrome
      - php
      - nginx
      - mysql
  chrome:
    image: "selenium/standalone-chrome-debug:latest"



